name = "portfolio-csp"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[ai]
binding = "AI"

routes = [{ pattern = "claudiaochoa.co/*", zone_name = "claudiaochoa.co" }]
